# Generated by Django 4.2 on 2023-04-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.TextField()),
                ('Phone', models.IntegerField()),
                ('Email', models.TextField()),
                ('Address', models.TextField()),
                ('Material', models.TextField()),
            ],
        ),
    ]
