# Generated by Django 4.1.7 on 2023-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='Department',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Material',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
